mysite/myapp/urls.py
from django.conf.urls import url
from . import views
from django.urls import path

app_name = 'myapp'

urlpatterns = [
    path('index/', views.index, name='index'),
    path('contacts/', views.contacts, name='contacts'),
    path('article1/', views.article1, name='article1'),
    path('article2/', views.article2, name='article2'),
    path('post/', views.post, name='post'),
    path('social/', views.social, name='social'),
    path('base/', views.post, name='base'),
    path('about/', views.about, name='about'),
    path('project/', views.project, name='project'),
    path('eduinfo/', views.edu_info, name='edu_info'),
    path('event/', views.event, name='event'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from myapp import views

urlpatterns = [
    url(r'^$',views.index1,name='index1'),
    path('admin/', admin.site.urls),
    #url(r'^$',v.index),
    path('', include('myapp.urls'))
]

#if settings.DEBUG:
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/myapp/models.py
from django.db import models

# Create your models here.

mysite/myapp/views.py
from django.shortcuts import render



# Create your views here.
def index(request):
    # return render_to_response('index.html')
    return render(request, 'index.html')

def index1(request):
    # return render_to_response('index.html')
    return render(request, 'index.html')

def contacts(request):
    return render(request, 'contact.html')

def article1(request):
    return render(request, 'article1.html')

def article2(request):
    return render(request, 'article2.html')

def post(request):
    return render(request, 'post.html')

def base(request):
    return render(request, 'base.html')

def social(request):
    return render(request, 'social.html')


def about(request):
    return render(request, 'about.html')

def event(request):

    return render(request, 'event.html')

def edu_info(request):
    return render(request, 'eduinfo.html')


def project(request):
    return render(request, 'project.html')

mysite/myapp/templates/about.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>My Blog</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

  <!-- Custom styles for this template -->
  <link href="{% static 'css/clean-blog.min.css' %}" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:about' %}">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:edu_info' %}">Educational Info</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:project' %}">Projects</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:event' %}">Technical Events</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:social' %}">Social contribution</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:post' %}">Blog</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:contacts' %}">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Header -->
  <header class="masthead" style="background-image: url('{% static 'img/open.jpg' %}')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="page-heading">
            <h1>About Me</h1>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Main Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <h1> Aditi Patil </h1>
        <img src="../static/img/aditi.jpg" alt="display this" width=200 height=200>
        <p> I am a TY CSE student at Walchand college of engineering, sangli<br><h3>My interests:</h3><ul>
          <li>solving problems</li>
          <li>logic Building</li>
          <li>solving puzzles</li>
          <li>spending time with friends</li>
        </ul><br>

        <h3>My favourite qoute:</h3>
        <blockquote cite="https://blog.hubspot.com/sales/famous-quotes" style="display: block;
        margin-top: 1em;
        margin-bottom: 1em;
        margin-left: 40px;
        margin-right: 40px;
        color: blue;">
        The greatest glory in living lies not in never falling, but in rising every time we fall
        </blockquote>

      </div>
    </div>
  </div>



  <!-- Footer -->

  <!-- Bootstrap core JavaScript -->
  <script src="{%  static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{%  static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Custom scripts for this template -->
  <script src="{% static 'js/clean-blog.min.js' %}"></script>

</body>

</html>

mysite/myapp/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">



<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:about' %}">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:edu_info' %}">Educational Info</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:project' %}">Projects</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:event' %}">Technical Events</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:post' %}">Blog</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:contacts' %}">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <script src="{%  static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{%  static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Custom scripts for this template -->
  <script src="{% static 'js/clean-blog.min.js' %}"></script>
  </body>

mysite/myapp/templates/contact.html
<!DOCTYPE html>
<html lang="en">

<head>
{%load static %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>My Blog</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

  <!-- Custom styles for this template -->
 <link href="{% static 'css/clean-blog.min.css' %}" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
<!--      <a class="navbar-brand" href="index.html">Start Bootstrap</a>-->
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">

        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:about' %}">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:edu_info' %}">Educational Info</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:project' %}">Projects</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:event' %}">Technical Events</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:social' %}">Social contribution</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:post' %}">Blog</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:contacts' %}">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>


  <!-- Page Header -->
  <header class="masthead" style="background-image: url('{% static 'img/contact.jpg' %}' )">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="page-heading">
            <h1>Contact Me</h1>
          </div>
        </div>
      </div>
    </div>
  </header>

  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="post-preview">
          <div class="description">
            <h3 >Contact Details</h3>
            <h5>Email:</h5>aditi.patil3900@gmail.com <br><h5>	Mob No: </h5>7249876055
            <h5>Address:</h5>Amnapur Road, Palus<br>Tal: Palus<br>Dist:Sangli<br>


          </div>


        </div>
      </div>
    </div>
  </div>


  <!-- Footer -->


  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Custom scripts for this template -->
  <script src="{% static 'js/clean-blog.min.js' %}"></script>
  <!-- Contact Form JavaScript -->
  <script src="{% static 'js/jqBootstrapValidation.js' %}"></script>
  <!--<script src="{% static 'js/contact_me.js' %}"></script>-->

  </body>

</html>

mysite/myapp/templates/eduinfo.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>My Blog</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

  <!-- Custom styles for this template -->
  <link href="{% static 'css/clean-blog.min.css' %}" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:about' %}">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:edu_info' %}">Educational Info</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:project' %}">Projects</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:event' %}">Technical Events</a></li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'myapp:social' %}">Social contribution</a>
            </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:post' %}">Blog</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:contacts' %}">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
<!-- Page Header -->
<header class="masthead" style="background-image: url('{% static 'img/education.jpg' %}')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="page-heading">
            <h1>Educational Info</h1>
            </div>
        </div>
      </div>
    </div>
  </header>
 {#main content#}
 <div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
      <div class="post-preview">


          <h2 >Secondary School</h2>
                <p >
Kirloskar Highschool, Kirloskarwadi  </br>Percentage: 95.20</p>
          <h2>Higher Education</h2>
            <p>SGM, Karad Percentage: 94.46 </br>CET: 155</p>
            <h2 >Btech</h2>
                <p >Walchand College Of Engineering,Sangli </br> CPI: 9.5</p>


      </div>
    </div>
  </div>
</div>



  <!-- Footer -->


  <!-- Bootstrap core JavaScript -->
  <script src="{%  static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{%  static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Custom scripts for this template -->
  <script src="{% static 'js/clean-blog.min.js' %}"></script>

</body>

</html>

mysite/myapp/templates/event.html
{% load static %}
{% static "img" as baseUrl %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>My Blog</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

  <!-- Custom styles for this template -->
  <link href="{% static 'css/clean-blog.min.css' %}" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:about' %}">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:edu_info' %}">Educational Info</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:project' %}">Projects</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:event' %}">Technical Events</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:social' %}">Social contribution</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:post' %}">Blog</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:contacts' %}">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
<!-- Page Header -->
<header class="masthead" style="background-image: url('{% static 'img/tech.jpg' %}')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="page-heading">
            <h1>Technical Events </h1>


          </div>
        </div>
      </div>
    </div>
  </div>
</header>
    <div class="container">
      <ul>
  <li><h5>Runner up in 4th national research symposiumWCE
2k19</h5></br>
<img src="../static/img/research.jpg" alt="display this" width=400 height=300></br></br></li>
  <li><h5>Best Aptitude award, Impulse 2k19</h5></br>
  <img src="../static/img/apti.jpg" alt="display this" width=400 height=300></br></br></li>
  <li><h5>Was the team leader of winning team, Impulse 2k19</h5></br>
  <img src="../static/img/team.jpg" alt="display this" width=400 height=300></br></br></li>
  <li><h5>shortlisted for SIH 2020 at WCE SIH</h5></br>
  <img src="../static/img/sih.jpg" alt="display this" width=400 height=300></br></br>
</li>
  <li><h5>Led a soft skills based event ELIPTAS at national level event Techumen 2019</h5></br></br></li>
  <li><h5>Delivered a session at C workshop 2019</h5>
</li>
</ul>






      </div>



  <!-- Footer -->


  <!-- Bootstrap core JavaScript -->
  <script src="{%  static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{%  static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Custom scripts for this template -->
  <script src="{% static 'js/clean-blog.min.js' %}"></script>

</body>

</html>

mysite/myapp/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>My Blog</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

  <!-- Custom styles for this template -->
  <link href="{% static 'css/clean-blog.min.css' %}" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">

      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:about' %}">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:edu_info' %}">Educational Info</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:project' %}">Projects</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:event' %}">Technical Events</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:social' %}">Social contribution</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:post' %}">Blog</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:contacts' %}">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Header -->
  <header class="masthead" style="background-image: url('{% static 'img/welcome1.jpg' %}') ">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h2>Hi, I'm Aditi Patil</h2>
            <span class="subheading">Welcome to my blog</span>
          </div>
        </div>
      </div>
    </div>
  </header>


  <!-- Footer -->


  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Custom scripts for this template -->
  <script src="{% static 'js/clean-blog.min.js' %}"></script>

</body>

</html>

mysite/myapp/templates/post.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>My Blog </title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

  <!-- Custom styles for this template -->
  <link href="{% static 'css/clean-blog.min.css' %}" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
<!--      <a class="navbar-brand" href="index.html">Start Bootstrap</a>-->
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:about' %}">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:edu_info' %}">Educational Info</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:project' %}">Projects</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:event' %}">Technical Events</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:social' %}">Social contribution</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:post' %}">Blog</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:contacts' %}">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Header -->
  <header class="masthead" style="background-image: url('{% static 'img/article.jpg' %}')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="post-heading">
            <h1>My Articles</h1>

          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Post Content -->
  <div class="container">

      <h2>You can view my articles here:</h2></br>
      <div >

        <ul>
    <li><h5><a  href="{% url 'myapp:article1' %}">Brain computer interface</a></h5></br>
  </li>

    <li><h5>
    <a  href="{% url 'myapp:article2' %}">Healthy living</a></h5></br>
    </li>

  </ul>


    </div>
  </div>


  <!-- Footer -->

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Custom scripts for this template -->
  <script src="{% static 'js/clean-blog.min.js' %}"></script>

</body>

</html>